services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: celery -A worker.worker:celery_app worker --loglevel=info
    restart: always
    depends_on:
      offload-task-broker:
        condition: service_healthy
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: amqp://offload:offload@offload-task-broker:5672//
      CELERY_RESULT_BACKEND: rpc://

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: celery -A worker.beat:celery_app beat --loglevel=info
    restart: always
    env_file:
      - .env
    depends_on:
      offload-task-broker:
        condition: service_healthy
    volumes:
      - celery-beat-data:/app/celerybeat

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: celery -A worker.celery_app flower --port=5555
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      offload-task-broker:
        condition: service_healthy
    restart: always

  offload-task-broker:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: offload
      RABBITMQ_DEFAULT_PASS: offload
    volumes:
      - offload-task-broker:/var/lib/rabbitmq
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  offload-task-broker:
  celery-beat-data:
